export interface PhoneCode {
  country: string;
  iso2: string;
  dial: string;
}

export const PHONE_CODES: PhoneCode[] = [
  { country: "Thailand",                         iso2: "th", dial: "+66"   },
  { country: "Afghanistan",                      iso2: "af", dial: "+93"   },
  { country: "Albania",                          iso2: "al", dial: "+355"  },
  { country: "Algeria",                          iso2: "dz", dial: "+213"  },
  { country: "Andorra",                          iso2: "ad", dial: "+376"  },
  { country: "Angola",                           iso2: "ao", dial: "+244"  },
  { country: "Antigua and Barbuda",              iso2: "ag", dial: "+1268" },
  { country: "Argentina",                        iso2: "ar", dial: "+54"   },
  { country: "Armenia",                          iso2: "am", dial: "+374"  },
  { country: "Australia",                        iso2: "au", dial: "+61"   },
  { country: "Austria",                          iso2: "at", dial: "+43"   },
  { country: "Azerbaijan",                       iso2: "az", dial: "+994"  },
  { country: "Bahamas",                          iso2: "bs", dial: "+1242" },
  { country: "Bahrain",                          iso2: "bh", dial: "+973"  },
  { country: "Bangladesh",                       iso2: "bd", dial: "+880"  },
  { country: "Barbados",                         iso2: "bb", dial: "+1246" },
  { country: "Belarus",                          iso2: "by", dial: "+375"  },
  { country: "Belgium",                          iso2: "be", dial: "+32"   },
  { country: "Belize",                           iso2: "bz", dial: "+501"  },
  { country: "Benin",                            iso2: "bj", dial: "+229"  },
  { country: "Bhutan",                           iso2: "bt", dial: "+975"  },
  { country: "Bolivia",                          iso2: "bo", dial: "+591"  },
  { country: "Bosnia and Herzegovina",           iso2: "ba", dial: "+387"  },
  { country: "Botswana",                         iso2: "bw", dial: "+267"  },
  { country: "Brazil",                           iso2: "br", dial: "+55"   },
  { country: "Brunei",                           iso2: "bn", dial: "+673"  },
  { country: "Bulgaria",                         iso2: "bg", dial: "+359"  },
  { country: "Burkina Faso",                     iso2: "bf", dial: "+226"  },
  { country: "Burundi",                          iso2: "bi", dial: "+257"  },
  { country: "Cabo Verde",                       iso2: "cv", dial: "+238"  },
  { country: "Cambodia",                         iso2: "kh", dial: "+855"  },
  { country: "Cameroon",                         iso2: "cm", dial: "+237"  },
  { country: "Canada",                           iso2: "ca", dial: "+1"    },
  { country: "Central African Republic",         iso2: "cf", dial: "+236"  },
  { country: "Chad",                             iso2: "td", dial: "+235"  },
  { country: "Chile",                            iso2: "cl", dial: "+56"   },
  { country: "China",                            iso2: "cn", dial: "+86"   },
  { country: "Colombia",                         iso2: "co", dial: "+57"   },
  { country: "Comoros",                          iso2: "km", dial: "+269"  },
  { country: "Congo (Brazzaville)",              iso2: "cg", dial: "+242"  },
  { country: "Congo (Kinshasa)",                 iso2: "cd", dial: "+243"  },
  { country: "Costa Rica",                       iso2: "cr", dial: "+506"  },
  { country: "Côte d'Ivoire",                    iso2: "ci", dial: "+225"  },
  { country: "Croatia",                          iso2: "hr", dial: "+385"  },
  { country: "Cuba",                             iso2: "cu", dial: "+53"   },
  { country: "Cyprus",                           iso2: "cy", dial: "+357"  },
  { country: "Czech Republic",                   iso2: "cz", dial: "+420"  },
  { country: "Denmark",                          iso2: "dk", dial: "+45"   },
  { country: "Djibouti",                         iso2: "dj", dial: "+253"  },
  { country: "Dominica",                         iso2: "dm", dial: "+1767" },
  { country: "Dominican Republic",               iso2: "do", dial: "+1809" },
  { country: "Ecuador",                          iso2: "ec", dial: "+593"  },
  { country: "Egypt",                            iso2: "eg", dial: "+20"   },
  { country: "El Salvador",                      iso2: "sv", dial: "+503"  },
  { country: "Equatorial Guinea",                iso2: "gq", dial: "+240"  },
  { country: "Eritrea",                          iso2: "er", dial: "+291"  },
  { country: "Estonia",                          iso2: "ee", dial: "+372"  },
  { country: "Eswatini",                         iso2: "sz", dial: "+268"  },
  { country: "Ethiopia",                         iso2: "et", dial: "+251"  },
  { country: "Fiji",                             iso2: "fj", dial: "+679"  },
  { country: "Finland",                          iso2: "fi", dial: "+358"  },
  { country: "France",                           iso2: "fr", dial: "+33"   },
  { country: "Gabon",                            iso2: "ga", dial: "+241"  },
  { country: "Gambia",                           iso2: "gm", dial: "+220"  },
  { country: "Georgia",                          iso2: "ge", dial: "+995"  },
  { country: "Germany",                          iso2: "de", dial: "+49"   },
  { country: "Ghana",                            iso2: "gh", dial: "+233"  },
  { country: "Greece",                           iso2: "gr", dial: "+30"   },
  { country: "Grenada",                          iso2: "gd", dial: "+1473" },
  { country: "Guatemala",                        iso2: "gt", dial: "+502"  },
  { country: "Guinea",                           iso2: "gn", dial: "+224"  },
  { country: "Guinea-Bissau",                    iso2: "gw", dial: "+245"  },
  { country: "Guyana",                           iso2: "gy", dial: "+592"  },
  { country: "Haiti",                            iso2: "ht", dial: "+509"  },
  { country: "Honduras",                         iso2: "hn", dial: "+504"  },
  { country: "Hungary",                          iso2: "hu", dial: "+36"   },
  { country: "Iceland",                          iso2: "is", dial: "+354"  },
  { country: "India",                            iso2: "in", dial: "+91"   },
  { country: "Indonesia",                        iso2: "id", dial: "+62"   },
  { country: "Iran",                             iso2: "ir", dial: "+98"   },
  { country: "Iraq",                             iso2: "iq", dial: "+964"  },
  { country: "Ireland",                          iso2: "ie", dial: "+353"  },
  { country: "Israel",                           iso2: "il", dial: "+972"  },
  { country: "Italy",                            iso2: "it", dial: "+39"   },
  { country: "Jamaica",                          iso2: "jm", dial: "+1876" },
  { country: "Japan",                            iso2: "jp", dial: "+81"   },
  { country: "Jordan",                           iso2: "jo", dial: "+962"  },
  { country: "Kazakhstan",                       iso2: "kz", dial: "+7"    },
  { country: "Kenya",                            iso2: "ke", dial: "+254"  },
  { country: "Kiribati",                         iso2: "ki", dial: "+686"  },
  { country: "Kuwait",                           iso2: "kw", dial: "+965"  },
  { country: "Kyrgyzstan",                       iso2: "kg", dial: "+996"  },
  { country: "Laos",                             iso2: "la", dial: "+856"  },
  { country: "Latvia",                           iso2: "lv", dial: "+371"  },
  { country: "Lebanon",                          iso2: "lb", dial: "+961"  },
  { country: "Lesotho",                          iso2: "ls", dial: "+266"  },
  { country: "Liberia",                          iso2: "lr", dial: "+231"  },
  { country: "Libya",                            iso2: "ly", dial: "+218"  },
  { country: "Liechtenstein",                    iso2: "li", dial: "+423"  },
  { country: "Lithuania",                        iso2: "lt", dial: "+370"  },
  { country: "Luxembourg",                       iso2: "lu", dial: "+352"  },
  { country: "Madagascar",                       iso2: "mg", dial: "+261"  },
  { country: "Malawi",                           iso2: "mw", dial: "+265"  },
  { country: "Malaysia",                         iso2: "my", dial: "+60"   },
  { country: "Maldives",                         iso2: "mv", dial: "+960"  },
  { country: "Mali",                             iso2: "ml", dial: "+223"  },
  { country: "Malta",                            iso2: "mt", dial: "+356"  },
  { country: "Marshall Islands",                 iso2: "mh", dial: "+692"  },
  { country: "Mauritania",                       iso2: "mr", dial: "+222"  },
  { country: "Mauritius",                        iso2: "mu", dial: "+230"  },
  { country: "Mexico",                           iso2: "mx", dial: "+52"   },
  { country: "Micronesia",                       iso2: "fm", dial: "+691"  },
  { country: "Moldova",                          iso2: "md", dial: "+373"  },
  { country: "Monaco",                           iso2: "mc", dial: "+377"  },
  { country: "Mongolia",                         iso2: "mn", dial: "+976"  },
  { country: "Montenegro",                       iso2: "me", dial: "+382"  },
  { country: "Morocco",                          iso2: "ma", dial: "+212"  },
  { country: "Mozambique",                       iso2: "mz", dial: "+258"  },
  { country: "Myanmar",                          iso2: "mm", dial: "+95"   },
  { country: "Namibia",                          iso2: "na", dial: "+264"  },
  { country: "Nauru",                            iso2: "nr", dial: "+674"  },
  { country: "Nepal",                            iso2: "np", dial: "+977"  },
  { country: "Netherlands",                      iso2: "nl", dial: "+31"   },
  { country: "New Zealand",                      iso2: "nz", dial: "+64"   },
  { country: "Nicaragua",                        iso2: "ni", dial: "+505"  },
  { country: "Niger",                            iso2: "ne", dial: "+227"  },
  { country: "Nigeria",                          iso2: "ng", dial: "+234"  },
  { country: "North Korea",                      iso2: "kp", dial: "+850"  },
  { country: "North Macedonia",                  iso2: "mk", dial: "+389"  },
  { country: "Norway",                           iso2: "no", dial: "+47"   },
  { country: "Oman",                             iso2: "om", dial: "+968"  },
  { country: "Pakistan",                         iso2: "pk", dial: "+92"   },
  { country: "Palau",                            iso2: "pw", dial: "+680"  },
  { country: "Palestine",                        iso2: "ps", dial: "+970"  },
  { country: "Panama",                           iso2: "pa", dial: "+507"  },
  { country: "Papua New Guinea",                 iso2: "pg", dial: "+675"  },
  { country: "Paraguay",                         iso2: "py", dial: "+595"  },
  { country: "Peru",                             iso2: "pe", dial: "+51"   },
  { country: "Philippines",                      iso2: "ph", dial: "+63"   },
  { country: "Poland",                           iso2: "pl", dial: "+48"   },
  { country: "Portugal",                         iso2: "pt", dial: "+351"  },
  { country: "Qatar",                            iso2: "qa", dial: "+974"  },
  { country: "Romania",                          iso2: "ro", dial: "+40"   },
  { country: "Russia",                           iso2: "ru", dial: "+7"    },
  { country: "Rwanda",                           iso2: "rw", dial: "+250"  },
  { country: "Saint Kitts and Nevis",            iso2: "kn", dial: "+1869" },
  { country: "Saint Lucia",                      iso2: "lc", dial: "+1758" },
  { country: "Saint Vincent and the Grenadines", iso2: "vc", dial: "+1784" },
  { country: "Samoa",                            iso2: "ws", dial: "+685"  },
  { country: "San Marino",                       iso2: "sm", dial: "+378"  },
  { country: "Sao Tome and Principe",            iso2: "st", dial: "+239"  },
  { country: "Saudi Arabia",                     iso2: "sa", dial: "+966"  },
  { country: "Senegal",                          iso2: "sn", dial: "+221"  },
  { country: "Serbia",                           iso2: "rs", dial: "+381"  },
  { country: "Seychelles",                       iso2: "sc", dial: "+248"  },
  { country: "Sierra Leone",                     iso2: "sl", dial: "+232"  },
  { country: "Singapore",                        iso2: "sg", dial: "+65"   },
  { country: "Slovakia",                         iso2: "sk", dial: "+421"  },
  { country: "Slovenia",                         iso2: "si", dial: "+386"  },
  { country: "Solomon Islands",                  iso2: "sb", dial: "+677"  },
  { country: "Somalia",                          iso2: "so", dial: "+252"  },
  { country: "South Africa",                     iso2: "za", dial: "+27"   },
  { country: "South Korea",                      iso2: "kr", dial: "+82"   },
  { country: "South Sudan",                      iso2: "ss", dial: "+211"  },
  { country: "Spain",                            iso2: "es", dial: "+34"   },
  { country: "Sri Lanka",                        iso2: "lk", dial: "+94"   },
  { country: "Sudan",                            iso2: "sd", dial: "+249"  },
  { country: "Suriname",                         iso2: "sr", dial: "+597"  },
  { country: "Sweden",                           iso2: "se", dial: "+46"   },
  { country: "Switzerland",                      iso2: "ch", dial: "+41"   },
  { country: "Syria",                            iso2: "sy", dial: "+963"  },
  { country: "Taiwan",                           iso2: "tw", dial: "+886"  },
  { country: "Tajikistan",                       iso2: "tj", dial: "+992"  },
  { country: "Tanzania",                         iso2: "tz", dial: "+255"  },
  { country: "Timor-Leste",                      iso2: "tl", dial: "+670"  },
  { country: "Togo",                             iso2: "tg", dial: "+228"  },
  { country: "Tonga",                            iso2: "to", dial: "+676"  },
  { country: "Trinidad and Tobago",              iso2: "tt", dial: "+1868" },
  { country: "Tunisia",                          iso2: "tn", dial: "+216"  },
  { country: "Turkey",                           iso2: "tr", dial: "+90"   },
  { country: "Turkmenistan",                     iso2: "tm", dial: "+993"  },
  { country: "Tuvalu",                           iso2: "tv", dial: "+688"  },
  { country: "Uganda",                           iso2: "ug", dial: "+256"  },
  { country: "Ukraine",                          iso2: "ua", dial: "+380"  },
  { country: "United Arab Emirates",             iso2: "ae", dial: "+971"  },
  { country: "United Kingdom",                   iso2: "gb", dial: "+44"   },
  { country: "United States",                    iso2: "us", dial: "+1"    },
  { country: "Uruguay",                          iso2: "uy", dial: "+598"  },
  { country: "Uzbekistan",                       iso2: "uz", dial: "+998"  },
  { country: "Vanuatu",                          iso2: "vu", dial: "+678"  },
  { country: "Vatican City",                     iso2: "va", dial: "+39"   },
  { country: "Venezuela",                        iso2: "ve", dial: "+58"   },
  { country: "Vietnam",                          iso2: "vn", dial: "+84"   },
  { country: "Yemen",                            iso2: "ye", dial: "+967"  },
  { country: "Zambia",                           iso2: "zm", dial: "+260"  },
  { country: "Zimbabwe",                         iso2: "zw", dial: "+263"  },
];

const DEFAULT_CODE = PHONE_CODES[0]; // Thailand

export function parsePhoneValue(value: string): { code: PhoneCode; number: string } {
  if (!value) return { code: DEFAULT_CODE, number: "" };
  const sorted = [...PHONE_CODES].sort((a, b) => b.dial.length - a.dial.length);
  for (const code of sorted) {
    if (value.startsWith(code.dial)) {
      return { code, number: value.slice(code.dial.length).trimStart() };
    }
  }
  return { code: DEFAULT_CODE, number: value };
}
